name: Run all tests

on:
  push:
    branches:
      - main

jobs:
  run-go-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
      - name: Install Protobuf Compiler
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.20'
      - name: Set up Protobuf Compiler in Go environment
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
      - name: Install libtspi-dev (see https://github.com/google/go-tpm-tools/issues/109)
        run: |
          sudo apt install -y libtspi-dev
      - name: Generate protobuf language bindings
        run: |
          make all
      - name: Build all sources
        run: |
          go get google.golang.org/grpc@v1.55.0
          go get github.com/google/tink/go/aead/subtle@v1.7.0
          go build ./...
      - name: Run all tests
        run: |
          go test ./...
